// Single source of truth: the Python detector outputs are imported at build
// time straight from data/demo/processed. No events, coordinates or statistics
// are hard-coded or duplicated here.

import eventsRaw from '../../data/demo/processed/events.json';
import summaryRaw from '../../data/demo/processed/detector_summary.json';
import replayRaw from '../../data/demo/processed/replay_sessions.json';
import roadIssuesRaw from '../../data/demo/processed/road_issues.json';

import type {
  DetectorSummary,
  EventClass,
  EventRecord,
  EventsFile,
  ReplayFile,
  ReplaySession,
  RoadIssue,
  RoadIssuesFile,
  RoadIssuesSummary,
} from './types';

export const eventsFile = eventsRaw as unknown as EventsFile;
export const summary = summaryRaw as unknown as DetectorSummary;
export const replayFile = replayRaw as unknown as ReplayFile;
export const roadIssuesFile = roadIssuesRaw as unknown as RoadIssuesFile;

/** Recorded RoadSens-4M sessions available for Journey Replay. */
export const replaySessions: ReplaySession[] = replayFile.sessions;

/** Proximity-based spatial issue clusters generated by the Python pipeline. */
export const roadIssues: RoadIssue[] = roadIssuesFile.issues;

/** Factual aggregation summary for the Road Issues view. */
export const roadIssuesSummary: RoadIssuesSummary = roadIssuesFile.summary;

/** Accepted events only (events.json already contains accepted events). */
export const acceptedEvents: EventRecord[] = eventsFile.events;

/** Candidates the detector suppressed, with an explicit reason. */
export const suppressedCandidates: EventRecord[] = eventsFile.suppressed_candidates;

/** Accepted events that carry real source GPS. Events without GPS are excluded. */
export const gpsEvents: EventRecord[] = acceptedEvents.filter(
  (event) => event.gps !== null,
);

export interface ClassMeta {
  label: string;
  color: string;
  rgb: string;
  description: string;
}

export const CLASS_META: Record<EventClass, ClassMeta> = {
  Pothole: {
    label: 'Pothole',
    color: '#f87171',
    rgb: '248, 113, 113',
    description: 'Source-supported RoadSens label.',
  },
  Bump: {
    label: 'Bump / Speed Breaker',
    color: '#fbbf24',
    rgb: '251, 191, 36',
    description: 'Source-supported RoadSens label.',
  },
  'Sustained Roughness': {
    label: 'Sustained Roughness',
    color: '#a78bfa',
    rgb: '167, 139, 250',
    description: 'Derived heuristic based on persistent vibration.',
  },
};

export function classMeta(eventClass: EventClass | null): ClassMeta | null {
  if (!eventClass) return null;
  return CLASS_META[eventClass] ?? null;
}

/** Human-readable labels for the detector evidence fields. */
export const EVIDENCE_LABELS: Record<string, string> = {
  peak_vertical_acceleration: 'Peak vertical acceleration (m/s²)',
  peak_abs_vertical_acceleration: 'Peak |vertical acceleration| (m/s²)',
  duration_seconds: 'Duration (s)',
  local_vibration_rms: 'Local vibration RMS (m/s²)',
  vertical_impulse: 'Vertical impulse',
  rebound_ratio: 'Rebound ratio',
  turning_activity: 'Turning activity (yaw)',
  horizontal_activity: 'Horizontal activity',
  gyroscope_magnitude: 'Gyroscope magnitude (rad/s)',
  mean_vertical_rms: 'Mean vertical RMS (m/s²)',
  peak_vertical_rms: 'Peak vertical RMS (m/s²)',
};

export const SUPPRESSION_LABELS: Record<string, string> = {
  turning: 'Turning',
  horizontal_motion: 'Horizontal motion',
  noise: 'Noise',
};

/** Stable identity for an event record across the JSON payload. */
export function eventKey(event: EventRecord): string {
  return `${event.session_id}:${event.class}:${event.start_row}:${event.peak_row ?? 'x'}`;
}

export function formatNumber(value: number, digits = 2): string {
  if (!Number.isFinite(value)) return '—';
  return value.toFixed(digits);
}

export function formatSeconds(value: number | null): string {
  if (value === null || !Number.isFinite(value)) return '—';
  return `${value.toFixed(2)} s`;
}

export function formatTimeRange(start: number | null, end: number | null): string {
  if (start === null || end === null) return '—';
  return `${start.toFixed(2)} s – ${end.toFixed(2)} s`;
}

export function formatCoords(gps: { latitude: number; longitude: number }): string {
  return `${gps.latitude.toFixed(6)}, ${gps.longitude.toFixed(6)}`;
}
